theme: jekyll-theme-slate
title: "2023 CIMPA School"
description: "Crossroads of geometry, representation theory and higher structures"


github:
  zip_url: site.github.zip_url
  another_url: _layouts/default.html
